"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0.6/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0.6/ref/settings/
"""
import os
# import django_heroku
# import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')9&b2*-19ld600y_3+g6liui5!d)kc-w)nj(xklm+tmj8#oj_d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['electroshop-fed348a3be5e.herokuapp.com', '8000-mayajj-electroshopecomm-ri6ac5zri5b.ws-us114.gitpod.io']

CSRF_COOKIE_DOMAIN = 'electroshop-fed348a3be5e.herokuapp.com'
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['electroshop-fed348a3be5e.herokuapp.com']
CSRF_COOKIE_DOMAIN = 'electroshop-fed348a3be5e.herokuapp.com'


# CSRF_COOKIE_DOMAIN = 'mayajj-electroshopecomm-ri6ac5zri5b.ws-us114.gitpod.io'
# CSRF_COOKIE_SECURE = True
# CSRF_TRUSTED_ORIGINS = ['https://8000-mayajj-electroshopecomm-ri6ac5zri5b.ws-us114.gitpod.io']
# CSRF_COOKIE_DOMAIN = '8000-mayajj-electroshopecomm-ri6ac5zri5b.ws-us114.gitpod.io'

SITE_ID = 1

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps
    'webapp1',

    # sitemap
    'django.contrib.sites',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0.6/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0.6/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0.6/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0.6/howto/static-files/


import os

# static files
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Adjust this path as needed

# django_heroku.settings(locals())

# for image upload
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'


#Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'advertise.website0994@gmail.com'
EMAIL_HOST_PASSWORD = 'rmzs syuu fewh bbos'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL= 'ecommerce <ecommerce@support>'


# stripe settings
STRIPE_PUBLISHABLE_KEY = 'pk_test_51IWuSRFzvY3Oon8K8D1ifAh7gdslJbsw3KJbpkDzsL6hD0Ghy3ofVA1xjLk5eZHOzZnUta8A0fykbjP0ScpxTe5m00PLxoAn9p'
STRIPE_SECRET_KEY = 'sk_test_51IWuSRFzvY3Oon8KHXlURApAt4rjhN1qKfh37Xvcwam0uzfvzZt8o3TJCirb5uFParGlho3a15S6V2s0mZLXsaOg00woMU6Fen'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'