# Generated by Django 3.1.7 on 2021-04-11 08:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=2000)),
                ('product_price', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='uploads/product_image')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='uploads/product_image')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp1.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=1000)),
                ('product_details', models.TextField()),
                ('total_bill', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('zip', models.CharField(max_length=1000)),
                ('ordered', models.BooleanField(default=False)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime(2021, 4, 11, 16, 46, 48, 944859))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=500)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Email-Confirmed',
            },
        ),
    ]
