# Generated by Django 3.1.7 on 2021-04-11 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0006_auto_20210411_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Your_has_been_packed',
            new_name='Your_order_has_been_packed',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 11, 16, 55, 18, 687124)),
        ),
    ]
