# Generated by Django 4.2.9 on 2024-01-06 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp1", "0010_auto_20210418_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 1, 6, 20, 50, 13, 911569)
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 6, 20, 50, 13, 911569)
            ),
        ),
    ]
