# Generated by Django 3.2.6 on 2024-01-09 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0011_alter_order_order_date_alter_reviews_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 10, 1, 4, 34, 925979)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 10, 1, 4, 34, 926978)),
        ),
    ]
