# Generated by Django 4.2.9 on 2024-01-12 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp1", "0013_auto_20240110_0104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 1, 12, 22, 20, 29, 16059)
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 12, 22, 20, 29, 17030)
            ),
        ),
    ]
