# Generated by Django 4.2.9 on 2024-01-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp1", "0015_alter_order_order_date_alter_reviews_review_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 1, 13, 0, 3, 10, 410510)
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="image2",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="image3",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="image4",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="products",
            name="image5",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 13, 0, 3, 10, 411440)
            ),
        ),
    ]
